import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import BottomNav from "@/components/BottomNav";
import AppChrome from "@/components/AppChrome";
import { PRODUCT_NAME } from "@/lib/branding";

const publicSans = localFont({
  src: "./fonts/public-sans-latin.woff2",
  weight: "100 900",
  variable: "--font-public-sans",
});

const barlowCondensed = localFont({
  src: [
    { path: "./fonts/barlow-condensed-700-latin.woff2", weight: "700" },
    { path: "./fonts/barlow-condensed-800-latin.woff2", weight: "800" },
    { path: "./fonts/barlow-condensed-900-latin.woff2", weight: "900" },
  ],
  variable: "--font-barlow-condensed",
});

export const metadata: Metadata = {
  title: PRODUCT_NAME,
  description: "Pick your situation, get the safe starting move, and go run it.",
  // The web app manifest is generated by app/manifest.ts (served at
  // /manifest.webmanifest); Next injects the <link rel="manifest"> automatically.
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#003087",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${publicSans.variable} ${barlowCondensed.variable} h-full`}>
      <body className="min-h-full bg-background text-foreground font-[family-name:var(--font-public-sans)]">
        <a
          href="#main-content"
          className="fixed left-4 top-2 z-[200] -translate-y-[150%] rounded-inner bg-white px-3.5 py-2.5 text-sm font-bold text-primary-dark shadow-modal focus:translate-y-0"
        >
          Skip to main content
        </a>
        <div className="max-w-lg md:max-w-3xl lg:max-w-6xl mx-auto min-h-screen relative lg:pl-20">
          <div className="bg-warm text-primary-dark text-center text-[10px] font-bold uppercase tracking-widest py-1.5 px-4">
            Concept demonstration. Plays are examples — check every draft before you sign it.
          </div>
          <AppChrome />
          <main id="main-content" tabIndex={-1} className="page-content">{children}</main>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
